### ISSUE TITLE
Some additions

### ISSUE THREAD

**Issue by jzaefferer** [sevenval/eslint-config-sevenval#11]
```
"quotes": [2, "single"],
"lines-around-comment": 0,
"react/no-array-index-key": 0,
"eol-last": ["error", "always"]
```
Disabling rules seems like something we should not include in the preset?

**Comment by marvinhagemeister** [comment]
I'm not sure about disabling `react/no-array-index-key`. Most of the time this can lead to a noticeable performance impact on lower end tablets/mobiles. The rest gets +1 from me 👍

**Comment by jzaefferer** [comment]
Okay. Leaving that one out, can the rest go in rules/base.js? Or is that all 'style'?
